

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: agricultural_db
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - smartfield_network

  authentication:
    build: ./microservicios/authentication
    environment:
      - FLASK_APP=app
      - FLASK_ENV=development
      - SQLALCHEMY_DATABASE_URI=postgresql://user:password@db/agricultural_db
    depends_on:
      - db
    ports:
      - "5001:5000"
    networks:
      - smartfield_network

  irrigation:
    build: ./microservicios/irrigation
    environment:
      - FLASK_APP=app
      - FLASK_ENV=development
      - SQLALCHEMY_DATABASE_URI=postgresql://user:password@db/agricultural_db
    depends_on:
      - db
    ports:
      - "5002:5000"
    networks:
      - smartfield_network

  monitoring:
    build: ./microservicios/monitoring
    environment:
      - FLASK_APP=app
      - FLASK_ENV=development
      - SQLALCHEMY_DATABASE_URI=postgresql://user:password@db/agricultural_db
    depends_on:
      - db
    ports:
      - "5003:5000"
    networks:
      - smartfield_network

  sensor:
    build: ./microservicios/sensor
    environment:
      - FLASK_APP=app
      - FLASK_ENV=development
      - SQLALCHEMY_DATABASE_URI=postgresql://user:password@db/agricultural_db
    depends_on:
      - db
    ports:
      - "5004:5000"
    networks:
      - smartfield_network

  gateway:
    build:
      context: ./microservicios/gateway  # Ruta a tu directorio del API Gateway
    ports:
      - "5000:5000"
    depends_on:
      - authentication
      - irrigation
      - monitoring
      - sensor
    environment:
      - FLASK_APP=gateway.py
      - FLASK_ENV=development
    networks:
      - smartfield_network

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    networks:
      - smartfield_network

volumes:
  pg_data:

networks:
  smartfield_network:
    driver: bridge

