

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: agricultural_db
    volumes:
      - pg_data:/var/lib/postgresql/data

  authentication:
    build: ./microservicios/authentication
    environment:
      - FLASK_APP=app
      - FLASK_ENV=development
      - SQLALCHEMY_DATABASE_URI=postgresql://user:password@db/agricultural_db
    depends_on:
      - db
    ports:
      - "5001:5000"

  irrigation:
    build: ./microservicios/irrigation
    environment:
      - FLASK_APP=app
      - FLASK_ENV=development
      - SQLALCHEMY_DATABASE_URI=postgresql://user:password@db/agricultural_db
    depends_on:
      - db
    ports:
      - "5002:5000"

  monitoring:
    build: ./microservicios/monitoring
    environment:
      - FLASK_APP=app
      - FLASK_ENV=development
      - SQLALCHEMY_DATABASE_URI=postgresql://user:password@db/agricultural_db
    depends_on:
      - db
    ports:
      - "5003:5000"

  sensor:
    build: ./microservicios/sensor
    environment:
      - FLASK_APP=app
      - FLASK_ENV=development
      - SQLALCHEMY_DATABASE_URI=postgresql://user:password@db/agricultural_db
    depends_on:
      - db
    ports:
      - "5004:5000"

volumes:
  pg_data:
